# General settings
data_dir: "data"
log_dir: "logs"
cache_dir: "cache"
log_level: "INFO"
max_retries: 3
retry_delay: 60
default_cache_duration: "30d"  # Default cache duration (30 days)

# Dataset-specific configurations
datasets:
  reanalysis-era5-pressure-levels:
    filename_pattern: "{dataset}_{variables}_{pressure}_{date}_{time}.{format}"
    max_retries: 5
    cache_duration: "30d"  # Cache for 7 days
    custom_validations:
      pressure_level:
        allowed_values: ['1000', '925', '850', '700', '500', '300', '250', '200', '100', '50']
        range: [0, 1000]
      time:
        allowed_values: ['00:00', '06:00', '12:00', '18:00']
    
  reanalysis-era5-single-levels:
    filename_pattern: "{dataset}_{variables}_{date}_{time}.{format}"
    cache_duration: "14d"  # Cache for 14 days
    custom_validations:
      time:
        allowed_values: ['00:00', '06:00', '12:00', '18:00']

# Cache duration format:
# Xh: X hours
# Xd: X days
# Xw: X weeks
# Xm: X months